// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Navya Advertising - Leading Event Management & Outdoor Advertising Agency",
  description: "Navya Advertising - Premier event management and outdoor advertising agency offering wedding planning, corporate events, brand activation, bus branding, hoarding ads, and comprehensive advertising solutions across all media.",
  keywords: "event management, advertising agency, wedding planning, corporate events, outdoor advertising, bus branding, hoarding ads, brand activation, wall painting, van branding, airport advertising, tricycle branding, artist management, social events, Navya Advertising",
  authors: [{ name: "Navya Advertising" }],
  creator: "Navya Advertising",
  publisher: "Navya Advertising",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://navyaadvertising.com'),
  alternates: {
    canonical: '/',
    languages: {
      'en-IN': '/',
    },
  },
  openGraph: {
    title: "Navya Advertising - Complete Event Management & Advertising Solutions",
    description: "Your trusted partner for event management and innovative advertising solutions including weddings, corporate events, bus branding, hoarding ads, and outdoor media campaigns.",
    url: 'https://navyaadvertising.com',
    siteName: 'Navya Advertising',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'Navya Advertising - Event Management & Advertising Agency',
      },
    ],
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: "Navya Advertising - Event Management & Advertising Agency",
    description: "Professional event planning and innovative advertising solutions for businesses and individuals.",
    images: ['/twitter-image.jpg'],
    creator: '@navyaadvertising',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    // Add your Google Search Console verification code here
    google: 'your-google-search-console-verification-code',
    // Add other verification codes as needed
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Structured Data for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "AdvertisingAgency",
              "name": "Navya Advertising",
              "description": "Professional event management and outdoor advertising agency providing comprehensive marketing solutions",
              "url": "https://navyaadvertising.com",
              "logo": "https://navyaadvertising.com/logo.png",
              "telephone": "+91-XXXXXXXXXX",
              "email": "info@navyaadvertising.com",
              "address": {
                "@type": "PostalAddress",
                "addressLocality": "Indore",
                "addressRegion": "MP",
                "postalCode": "452001",
                "addressCountry": "IN"
              },
              "geo": {
                "@type": "GeoCoordinates",
                "latitude": "Your Latitude",
                "longitude": "Your Longitude"
              },
              "openingHours": "Mo-Su 09:00-20:00",
              "serviceType": [
                "Event Management",
                "Wedding Planning",
                "Corporate Events",
                "Outdoor Advertising",
                "Bus Branding",
                "Hoarding Advertising",
                "Van Branding",
                "Wall Painting",
                "Airport Advertising",
                "Tricycle Branding",
                "Brand Activation",
                "Artist Management"
              ],
              "areaServed": ["Indore", "MP", "India"],
              "sameAs": [
                "https://www.facebook.com/navyaadvertising",
                "https://www.instagram.com/navyaadvertising",
                "https://www.linkedin.com/company/navyaadvertising"
              ]
            })
          }}
        />
        
        {/* Additional Schema for Local Business */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "name": "Navya Advertising",
              "image": "https://navyaadvertising.com/logo.png",
              "@id": "https://navyaadvertising.com",
              "url": "https://navyaadvertising.com",
              "telephone": "+91-XXXXXXXXXX",
              "address": {
                "@type": "PostalAddress",
                "streetAddress": "Office No. 404, The Heritage, 582 Mahatma Gandhi Rd",
                "addressLocality": "Indore",
                "addressRegion": "MP",
                "postalCode": "452001",
                "addressCountry": "IN"
              },
              "geo": {
                "@type": "GeoCoordinates",
                "latitude": "Your Latitude",
                "longitude": "Your Longitude"
              },
              "openingHoursSpecification": {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                  "Sunday"
                ],
                "opens": "09:00",
                "closes": "20:00"
              },
              "sameAs": [
                "https://www.facebook.com/navyaadvertising",
                "https://www.instagram.com/navyaadvertising",
                "https://www.linkedin.com/company/navyaadvertising"
              ]
            })
          }}
        />

        {/* Favicon Links */}
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
        
        {/* Preconnect to important domains */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Canonical URL */}
        <link rel="canonical" href="https://navyaadvertising.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
